/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupplierRouteImport } from './routes/supplier'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SupplierIndexRouteImport } from './routes/supplier/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as SupplierProductsRouteImport } from './routes/supplier/products'
import { Route as ProductProductIdRouteImport } from './routes/product/$productId'
import { Route as SupplierProductsIndexRouteImport } from './routes/supplier/products/index'
import { Route as SupplierProductsNewRouteImport } from './routes/supplier/products/new'

const SupplierRoute = SupplierRouteImport.update({
  id: '/supplier',
  path: '/supplier',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplierIndexRoute = SupplierIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SupplierRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SupplierProductsRoute = SupplierProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => SupplierRoute,
} as any)
const ProductProductIdRoute = ProductProductIdRouteImport.update({
  id: '/product/$productId',
  path: '/product/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplierProductsIndexRoute = SupplierProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SupplierProductsRoute,
} as any)
const SupplierProductsNewRoute = SupplierProductsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => SupplierProductsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/supplier': typeof SupplierRouteWithChildren
  '/product/$productId': typeof ProductProductIdRoute
  '/supplier/products': typeof SupplierProductsRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/supplier/': typeof SupplierIndexRoute
  '/supplier/products/new': typeof SupplierProductsNewRoute
  '/supplier/products/': typeof SupplierProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/admin': typeof AdminIndexRoute
  '/supplier': typeof SupplierIndexRoute
  '/supplier/products/new': typeof SupplierProductsNewRoute
  '/supplier/products': typeof SupplierProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/supplier': typeof SupplierRouteWithChildren
  '/product/$productId': typeof ProductProductIdRoute
  '/supplier/products': typeof SupplierProductsRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/supplier/': typeof SupplierIndexRoute
  '/supplier/products/new': typeof SupplierProductsNewRoute
  '/supplier/products/': typeof SupplierProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/checkout'
    | '/login'
    | '/products'
    | '/profile'
    | '/register'
    | '/supplier'
    | '/product/$productId'
    | '/supplier/products'
    | '/admin/'
    | '/supplier/'
    | '/supplier/products/new'
    | '/supplier/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/login'
    | '/products'
    | '/profile'
    | '/register'
    | '/product/$productId'
    | '/admin'
    | '/supplier'
    | '/supplier/products/new'
    | '/supplier/products'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/checkout'
    | '/login'
    | '/products'
    | '/profile'
    | '/register'
    | '/supplier'
    | '/product/$productId'
    | '/supplier/products'
    | '/admin/'
    | '/supplier/'
    | '/supplier/products/new'
    | '/supplier/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CheckoutRoute: typeof CheckoutRoute
  LoginRoute: typeof LoginRoute
  ProductsRoute: typeof ProductsRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  SupplierRoute: typeof SupplierRouteWithChildren
  ProductProductIdRoute: typeof ProductProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/supplier': {
      id: '/supplier'
      path: '/supplier'
      fullPath: '/supplier'
      preLoaderRoute: typeof SupplierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplier/': {
      id: '/supplier/'
      path: '/'
      fullPath: '/supplier/'
      preLoaderRoute: typeof SupplierIndexRouteImport
      parentRoute: typeof SupplierRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/supplier/products': {
      id: '/supplier/products'
      path: '/products'
      fullPath: '/supplier/products'
      preLoaderRoute: typeof SupplierProductsRouteImport
      parentRoute: typeof SupplierRoute
    }
    '/product/$productId': {
      id: '/product/$productId'
      path: '/product/$productId'
      fullPath: '/product/$productId'
      preLoaderRoute: typeof ProductProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplier/products/': {
      id: '/supplier/products/'
      path: '/'
      fullPath: '/supplier/products/'
      preLoaderRoute: typeof SupplierProductsIndexRouteImport
      parentRoute: typeof SupplierProductsRoute
    }
    '/supplier/products/new': {
      id: '/supplier/products/new'
      path: '/new'
      fullPath: '/supplier/products/new'
      preLoaderRoute: typeof SupplierProductsNewRouteImport
      parentRoute: typeof SupplierProductsRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface SupplierProductsRouteChildren {
  SupplierProductsNewRoute: typeof SupplierProductsNewRoute
  SupplierProductsIndexRoute: typeof SupplierProductsIndexRoute
}

const SupplierProductsRouteChildren: SupplierProductsRouteChildren = {
  SupplierProductsNewRoute: SupplierProductsNewRoute,
  SupplierProductsIndexRoute: SupplierProductsIndexRoute,
}

const SupplierProductsRouteWithChildren =
  SupplierProductsRoute._addFileChildren(SupplierProductsRouteChildren)

interface SupplierRouteChildren {
  SupplierProductsRoute: typeof SupplierProductsRouteWithChildren
  SupplierIndexRoute: typeof SupplierIndexRoute
}

const SupplierRouteChildren: SupplierRouteChildren = {
  SupplierProductsRoute: SupplierProductsRouteWithChildren,
  SupplierIndexRoute: SupplierIndexRoute,
}

const SupplierRouteWithChildren = SupplierRoute._addFileChildren(
  SupplierRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  LoginRoute: LoginRoute,
  ProductsRoute: ProductsRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  SupplierRoute: SupplierRouteWithChildren,
  ProductProductIdRoute: ProductProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
