/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupplierRouteImport } from './routes/supplier'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as SupplierIndexRouteImport } from './routes/supplier/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PublicIndexRouteImport } from './routes/_public.index'
import { Route as SupplierProductsRouteImport } from './routes/supplier/products'
import { Route as AdminInventoryRouteImport } from './routes/admin/inventory'
import { Route as PublicRegisterRouteImport } from './routes/_public.register'
import { Route as PublicProfileRouteImport } from './routes/_public.profile'
import { Route as PublicProductsRouteImport } from './routes/_public.products'
import { Route as PublicLoginRouteImport } from './routes/_public.login'
import { Route as PublicCheckoutRouteImport } from './routes/_public.checkout'
import { Route as SupplierProductsIndexRouteImport } from './routes/supplier/products/index'
import { Route as SupplierProductsNewRouteImport } from './routes/supplier/products/new'
import { Route as PublicProductProductIdRouteImport } from './routes/_public.product.$productId'

const SupplierRoute = SupplierRouteImport.update({
  id: '/supplier',
  path: '/supplier',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplierIndexRoute = SupplierIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SupplierRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const SupplierProductsRoute = SupplierProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => SupplierRoute,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminRoute,
} as any)
const PublicRegisterRoute = PublicRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => PublicRoute,
} as any)
const PublicProfileRoute = PublicProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PublicRoute,
} as any)
const PublicProductsRoute = PublicProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const PublicCheckoutRoute = PublicCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => PublicRoute,
} as any)
const SupplierProductsIndexRoute = SupplierProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SupplierProductsRoute,
} as any)
const SupplierProductsNewRoute = SupplierProductsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => SupplierProductsRoute,
} as any)
const PublicProductProductIdRoute = PublicProductProductIdRouteImport.update({
  id: '/product/$productId',
  path: '/product/$productId',
  getParentRoute: () => PublicRoute,
} as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminRouteWithChildren
  '/supplier': typeof SupplierRouteWithChildren
  '/checkout': typeof PublicCheckoutRoute
  '/login': typeof PublicLoginRoute
  '/products': typeof PublicProductsRoute
  '/profile': typeof PublicProfileRoute
  '/register': typeof PublicRegisterRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/supplier/products': typeof SupplierProductsRouteWithChildren
  '/': typeof PublicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/supplier/': typeof SupplierIndexRoute
  '/product/$productId': typeof PublicProductProductIdRoute
  '/supplier/products/new': typeof SupplierProductsNewRoute
  '/supplier/products/': typeof SupplierProductsIndexRoute
}
export interface FileRoutesByTo {
  '/checkout': typeof PublicCheckoutRoute
  '/login': typeof PublicLoginRoute
  '/products': typeof PublicProductsRoute
  '/profile': typeof PublicProfileRoute
  '/register': typeof PublicRegisterRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminIndexRoute
  '/supplier': typeof SupplierIndexRoute
  '/product/$productId': typeof PublicProductProductIdRoute
  '/supplier/products/new': typeof SupplierProductsNewRoute
  '/supplier/products': typeof SupplierProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/supplier': typeof SupplierRouteWithChildren
  '/_public/checkout': typeof PublicCheckoutRoute
  '/_public/login': typeof PublicLoginRoute
  '/_public/products': typeof PublicProductsRoute
  '/_public/profile': typeof PublicProfileRoute
  '/_public/register': typeof PublicRegisterRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/supplier/products': typeof SupplierProductsRouteWithChildren
  '/_public/': typeof PublicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/supplier/': typeof SupplierIndexRoute
  '/_public/product/$productId': typeof PublicProductProductIdRoute
  '/supplier/products/new': typeof SupplierProductsNewRoute
  '/supplier/products/': typeof SupplierProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/supplier'
    | '/checkout'
    | '/login'
    | '/products'
    | '/profile'
    | '/register'
    | '/admin/inventory'
    | '/supplier/products'
    | '/'
    | '/admin/'
    | '/supplier/'
    | '/product/$productId'
    | '/supplier/products/new'
    | '/supplier/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/checkout'
    | '/login'
    | '/products'
    | '/profile'
    | '/register'
    | '/admin/inventory'
    | '/'
    | '/admin'
    | '/supplier'
    | '/product/$productId'
    | '/supplier/products/new'
    | '/supplier/products'
  id:
    | '__root__'
    | '/_public'
    | '/admin'
    | '/supplier'
    | '/_public/checkout'
    | '/_public/login'
    | '/_public/products'
    | '/_public/profile'
    | '/_public/register'
    | '/admin/inventory'
    | '/supplier/products'
    | '/_public/'
    | '/admin/'
    | '/supplier/'
    | '/_public/product/$productId'
    | '/supplier/products/new'
    | '/supplier/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  SupplierRoute: typeof SupplierRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/supplier': {
      id: '/supplier'
      path: '/supplier'
      fullPath: '/supplier'
      preLoaderRoute: typeof SupplierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplier/': {
      id: '/supplier/'
      path: '/'
      fullPath: '/supplier/'
      preLoaderRoute: typeof SupplierIndexRouteImport
      parentRoute: typeof SupplierRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/supplier/products': {
      id: '/supplier/products'
      path: '/products'
      fullPath: '/supplier/products'
      preLoaderRoute: typeof SupplierProductsRouteImport
      parentRoute: typeof SupplierRoute
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/register': {
      id: '/_public/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof PublicRegisterRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/profile': {
      id: '/_public/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof PublicProfileRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/products': {
      id: '/_public/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof PublicProductsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/checkout': {
      id: '/_public/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof PublicCheckoutRouteImport
      parentRoute: typeof PublicRoute
    }
    '/supplier/products/': {
      id: '/supplier/products/'
      path: '/'
      fullPath: '/supplier/products/'
      preLoaderRoute: typeof SupplierProductsIndexRouteImport
      parentRoute: typeof SupplierProductsRoute
    }
    '/supplier/products/new': {
      id: '/supplier/products/new'
      path: '/new'
      fullPath: '/supplier/products/new'
      preLoaderRoute: typeof SupplierProductsNewRouteImport
      parentRoute: typeof SupplierProductsRoute
    }
    '/_public/product/$productId': {
      id: '/_public/product/$productId'
      path: '/product/$productId'
      fullPath: '/product/$productId'
      preLoaderRoute: typeof PublicProductProductIdRouteImport
      parentRoute: typeof PublicRoute
    }
  }
}

interface PublicRouteChildren {
  PublicCheckoutRoute: typeof PublicCheckoutRoute
  PublicLoginRoute: typeof PublicLoginRoute
  PublicProductsRoute: typeof PublicProductsRoute
  PublicProfileRoute: typeof PublicProfileRoute
  PublicRegisterRoute: typeof PublicRegisterRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicProductProductIdRoute: typeof PublicProductProductIdRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicCheckoutRoute: PublicCheckoutRoute,
  PublicLoginRoute: PublicLoginRoute,
  PublicProductsRoute: PublicProductsRoute,
  PublicProfileRoute: PublicProfileRoute,
  PublicRegisterRoute: PublicRegisterRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicProductProductIdRoute: PublicProductProductIdRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface AdminRouteChildren {
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminInventoryRoute: AdminInventoryRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface SupplierProductsRouteChildren {
  SupplierProductsNewRoute: typeof SupplierProductsNewRoute
  SupplierProductsIndexRoute: typeof SupplierProductsIndexRoute
}

const SupplierProductsRouteChildren: SupplierProductsRouteChildren = {
  SupplierProductsNewRoute: SupplierProductsNewRoute,
  SupplierProductsIndexRoute: SupplierProductsIndexRoute,
}

const SupplierProductsRouteWithChildren =
  SupplierProductsRoute._addFileChildren(SupplierProductsRouteChildren)

interface SupplierRouteChildren {
  SupplierProductsRoute: typeof SupplierProductsRouteWithChildren
  SupplierIndexRoute: typeof SupplierIndexRoute
}

const SupplierRouteChildren: SupplierRouteChildren = {
  SupplierProductsRoute: SupplierProductsRouteWithChildren,
  SupplierIndexRoute: SupplierIndexRoute,
}

const SupplierRouteWithChildren = SupplierRoute._addFileChildren(
  SupplierRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  SupplierRoute: SupplierRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
